### ISSUE TITLE
Error in assembly manual - page 10 and 14 - Wrong extrusions marked

### ISSUE THREAD

**Issue by internallabworks** [VoronDesign/Voron-Switchwire#12]
On page 10, the uprights for Z is marked for use for the bottom cross extrusions.
And on page 14 the cross extrusions are marked for use on Z
Example on page 10:
![image](https://user-images.githubusercontent.com/64136358/106013142-78b24800-60bc-11eb-8c66-5cd25ca946e3.png)

Makes the bottom look funky wide :)
![image](https://user-images.githubusercontent.com/64136358/106013359-a9927d00-60bc-11eb-8613-2b5a842732c8.png)

**Comment by jakep82** [comment]
This issue was reintroduced in the manual that was published 19 days ago. I just built my frame and discovered it called for the wrong extrusions, requiring me to disassemble and start over.

**Comment by raymondh2** [comment]
This issue has been resolved by #13
