### ISSUE TITLE
Missing Part in BOM: Bowden tube

### ISSUE THREAD

**Issue by digitalfrost** [VoronDesign/Voron-Switchwire#15]
On the page https://vorondesign.com/voron_switchwire when clicking on the BOM button, the BOM displayed and available for download as voron_switchwire_bom.csv seems to have a part missing.

It is not consistent with the information given in the sourcing guide: https://vorondesign.com/sourcing_guide?model=VS

Under the Misc section the 
_Bowden Tube (4mm OD, 3mm ID) | 3m_
listed in the sourcing guide is missing from the downloadable sourcing guide.

**Comment by raymondh2** [comment]
The 3mm id bowden tube is an optional item on Switchwire
