### ISSUE TITLE
Incorrect / Old Klipper Configs.

### ISSUE THREAD

**Issue by cobramike** [VoronDesign/Voron-Switchwire#27]
After a full month of testing and fine tuning i made a Correct fysetc spider printer.cfg.
The old firmware are a very old Klipper config. Also extruder settings are incorrect. That is causing extreme heat Extruder Motor.
Here is my Printer.cfg for the fysetc spider

[https://pastebin.com/VuUeXtPq](url)

#####################################################################
# 	Printer settings
#####################################################################
[mcu]
serial: /dev/ttyAMA0
restart_method: command

[printer]
kinematics: corexz
max_velocity: 200
max_accel: 4000
max_accel_to_decel: 4000
max_z_velocity: 50
max_z_accel: 1000
square_corner_velocity: 4.0

[input_shaper]
shaper_freq_x: 52
shaper_freq_y: 54.5
shaper_type: mzv

[stepper_x]
step_pin: PE11
dir_pin: !PE10
enable_pin: !PE9
endstop_pin: ^PB14
position_endstop: 250
position_min: 0
position_max: 250
homing_speed: 70
homing_positive_dir: true
rotation_distance: 40
full_steps_per_rotation: 200
microsteps: 16

[tmc2209 stepper_x]
uart_pin: PE7
run_current: 0.5
hold_current: 0.3
interpolate: True
stealthchop_threshold: 250

[stepper_y]
step_pin: PD8
dir_pin: !PB12
enable_pin: !PD9
endstop_pin: ^PB13
position_endstop: 250
position_min: 0
position_max: 250
homing_speed: 70
homing_positive_dir: true
rotation_distance: 40
full_steps_per_rotation: 200
microsteps: 16

[tmc2209 stepper_y]
uart_pin: PE15
run_current: 0.6
hold_current: 0.4
interpolate: True
stealthchop_threshold: 250

[stepper_z]
step_pin: PD14
dir_pin: !PD13
enable_pin: !PD15
endstop_pin: probe:z_virtual_endstop
position_max: 235
homing_speed: 40
position_min: -3.0
rotation_distance: 40
full_steps_per_rotation: 200
microsteps: 16

[tmc2209 stepper_z]
uart_pin: PD10
run_current: 0.5
hold_current: 0.3
interpolate: True
stealthchop_threshold: 250

[bed_mesh]
speed: 150
horizontal_move_z: 10
mesh_min: 25,35.0
mesh_max: 225.0,220
probe_count: 6,6
algorithm: bicubic
fade_start: 1
fade_end: 10
fade_target: 0

[probe]
pin: PA3
x_offset: 0.0
y_offset: 25.0
#z_offset: 0
speed: 40.0

[homing_override]
axes: z
set_position_z: 0
gcode:
    G90
    G0 Z5 F500
    G28 X0 Y0
    G0 X125 Y100 F9000
    G28 Z0
    G0 Z5 F500

#####################################################################
# 	Extruder
#####################################################################

#	E0 on MCU X/Y
[extruder]
max_extrude_only_distance: 1000.0
step_pin: PD5
dir_pin: !PD6
enable_pin: !PD4
##  22.6789511 is a good starting point
rotation_distance: 22.225372078 	#Bondtech 5mm Drive Gears
##	Use 80:20 for M4, M3.1
gear_ratio: 50:17				#BMG Gear Ratio
microsteps: 16
full_steps_per_rotation: 200	#200 for 1.8 degree, 400 for 0.9 degree
nozzle_diameter: 0.400
filament_diameter: 1.75
heater_pin: PB15
##	Validate the following thermistor type to make sure it is correct
sensor_type: ATC Semitec 104GT-2
sensor_pin: PC0
min_temp: 10
max_temp: 270
max_power: 1.0
min_extrude_temp: 170
control = pid
pid_kp = 26.213
pid_ki = 1.304
pid_kd = 131.721
##	Try to keep pressure_advance below 1.0
pressure_advance: 0.05
##	Default is 0.040, leave stock
pressure_advance_smooth_time: 0.040

##	Make sure to update below for your relevant driver (2208 or 2209)
[tmc2209 extruder]
uart_pin: PD7
interpolate: false
run_current: 0.45
hold_current: 0.30
sense_resistor: 0.110
stealthchop_threshold: 0

#####################################################################
# 	END Extruder
#####################################################################

#####################################################################
# 	Probe Settings
#####################################################################
# Textured Bed
#[probe]
#z_offset = 4.910

# Flat Bed
[probe]
z_offset = 4.740

#####################################################################
# 	End Probe Settings
#####################################################################

[heater_bed]
heater_pin: PB4
sensor_type: NTC 100K MGB18-104F39050L32
sensor_pin: PC3
control = pid
pid_kp = 60.695
pid_ki = 1.073
pid_kd = 858.069
min_temp: 0
max_temp: 130

#######################################
#######################################
[temperature_sensor enclosure_temp]
sensor_type: NTC 100K beta 3950
sensor_pin: PC1
min_temp: 0
max_temp: 100
gcode_id: C

#######################################
#######################################
[temperature_sensor Pi]
sensor_type: rpi_temperature
min_temp: 0
max_temp: 90

[fan] 
pin: PB2

# thermally controlled hotend fan
[heater_fan my_nozzle_fan]
pin: PB1
max_power: 1.0
kick_start_time: 0.100
heater: extruder
heater_temp: 50.0
fan_speed: 1.0

[virtual_sdcard]
path: ~/gcode_files

#####################################################################
#	Displays
#####################################################################

[display]
#   mini12864 LCD Display
lcd_type: uc1701
cs_pin: PC11
a0_pin: PD2
rst_pin: PC10
encoder_pins: ^PC6,^PC7
click_pin: ^!PA8
contrast: 63
#spi_bus: spi1
spi_software_mosi_pin: PA7
spi_software_miso_pin: PA6
spi_software_sclk_pin: PA5

[neopixel fysetc_mini12864]
#   To control Neopixel RGB in mini12864 display
pin: PC12
chain_count: 3
chain_count: 60
initial_RED: 0.1
initial_GREEN: 0.5
initial_BLUE: 0.0
color_order: RGB

#   Set RGB values on boot up for each Neopixel. 
#   Index 1 = display, Index 2 and 3 = Knob
[delayed_gcode setdisplayneopixel]
initial_duration: 1
gcode:
    SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=1 TRANSMIT=0
    SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=2 TRANSMIT=0
    SET_LED LED=fysetc_mini12864 RED=1 GREEN=0 BLUE=0 INDEX=3 

#####################################################################
#	LED Control
#####################################################################

# Chamber Lighting
[output_pin caselight]
pin: PB3
#max_power: 1.0
#kick_start_time: 0.5
pwm: true
shutdown_value: 0
value: 100
cycle_time: 0.01
scale: 100
 
# Lighting Control
[gcode_macro lights_off]
gcode:
    SET_PIN PIN=caselight VALUE=0
 
[gcode_macro lights_on]
gcode:
    SET_PIN PIN=caselight VALUE=100
	
#####################################################################
#	End LED Control
#####################################################################

#####################################################################
#	Macros
#####################################################################
[display_status]

[pause_resume]

[gcode_macro CANCEL_PRINT]
rename_existing: BASE_CANCEL_PRINT
gcode:
    M107
    TURN_OFF_HEATERS
    DISABLE_MOTORS
    CLEAR_PAUSE
    SDCARD_RESET_FILE
    BASE_CANCEL_PRINT

[gcode_macro PAUSE]
rename_existing: BASE_PAUSE
gcode:
    SAVE_GCODE_STATE NAME=PAUSE_state
    BASE_PAUSE
    G91
    G1 E-1.7 F2100
    G90
    _PARK_HEAD

[gcode_macro RESUME]
rename_existing: BASE_RESUME
gcode:
    G91
    G1 E1.7 F2100
    G91
    RESTORE_GCODE_STATE NAME=PAUSE_state MOVE=1
    BASE_RESUME

[gcode_macro DISABLE_MOTORS]
gcode:
    M18

[gcode_macro PRINT_START]
gcode:
    lights_on
    M117 Homing...
    M140 S{BED_TEMP}                         ; set bed final temp
    M104 S{EXTRUDER_TEMP}                         ; set extruder final temp
    M190 S{BED_TEMP}                         ; wait for bed final temp
    M109 S{EXTRUDER_TEMP}                         ; wait for extruder final temp
    BED_MESH_CLEAR

    G21 ; set units to millimeters
    G90 ; use absolute coordinates
    M83 ; use relative distances for extrusion
    G28 ; home all axes
    G1 Z20 F3000                   ; move nozzle away from bed
    BED_MESH_CALIBRATE
    G92 E0
    G90
    G0 X13 Y13 F6000
    G0 Z0.4
    G91
    G1 X120 E30 F1200
    G1 Y1
    G1 X-120 E30 F1200
    G92 E0
    G90
    G1 Z20.0 F3000
    G92 E0
    M117 Printing....

[gcode_macro PRINT_END]
#   Use PRINT_END for the slicer ending script - please customise for your slicer of choice
gcode:
    M400                           ; wait for buffer to clear
    G92 E0                         ; zero the extruder
    G1 E-1.0 F3600                ; retract filament
    G91                            ; relative positioning
    G0 Z1.00 X20.0 Y20.0 F20000    ; move nozzle to remove stringing
    TURN_OFF_HEATERS
    M107                           ; turn off fan
    G1 Z50 F3000                    ; move nozzle up 20mm
    G90                            ; absolute positioning
    G0  X0 Y220 F3600            ; park nozzle at rear
    BED_MESH_CLEAR
    M117 Finished!
    lights_off

#####################################################################
#	End Macros
#####################################################################

#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#

**Comment by raymondh2** [comment]
Fixed in #31
