### ISSUE TITLE
switchwire stl and cad files out of synch

### ISSUE THREAD

**Issue by phongshader** [VoronDesign/Voron-Switchwire#36]
it looks like https://github.com/VoronDesign/Voron-Switchwire/blob/master/STL/Gantry/XZ_Axis/%5Ba%5D_upper_idler_support_b_left.stl and https://github.com/VoronDesign/Voron-Switchwire/blob/master/STL/Gantry/XZ_Axis/%5Ba%5D_upper_idler_support_b_right.stl are a different version than what is contained here https://github.com/VoronDesign/Voron-Switchwire/blob/master/CAD/Bowden_Dual_Adapter.step. Is it possible to get the updated files in step or f3d?

**Comment by nemgrea** [comment]
the files youve linked are not the same parts, the bowden toolhead CAD is not intended to contain any of the idler parts
