### ISSUE TITLE
Y-CARRIAGE

### ISSUE THREAD

**Issue by anlox31** [VoronDesign/Voron-Switchwire#47]
where are you find y carriage cad file ?

**Comment by jernejp21** [comment]
All the CAD models are in a single CAD file - printer assembly file.
https://github.com/VoronDesign/Voron-Switchwire/blob/master/CAD/Switchwire_Assembly_v1.13.f3d

**Comment by anlox31** [comment]
can i used for hot bed size 220mm ?

**Comment by nemgrea** [comment]
this seems to be a request for help and not a valid issue report
