### ISSUE TITLE
Manual has extra hole on pages 31 and 55

### ISSUE THREAD

**Issue by Kozova1** [VoronDesign/Voron-Switchwire#49]
In the triangle pattern cable chain mount
![image](https://user-images.githubusercontent.com/30871100/197344038-314b8b9a-811f-4472-b2dd-4c3784d315e9.png)
![image](https://user-images.githubusercontent.com/30871100/197345122-3afb816a-a9bd-47cf-843c-5acb33002002.png)

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Switchwire/pull/59
