### ISSUE TITLE
Build guide of some sorts?

### ISSUE THREAD

**Issue by tobyworks** [VoronDesign/Voron-Switchwire#5]
Maybe I'm blind but i've searched for build guides or how to's or anything close to that and i couldn't find one? is it still on the to-do?

**Comment by raymondh2** [comment]
The manual is in progress still

**Comment by mild-lemon** [comment]
Any target date for a pre-alpha version of the manual?
I'm considering building a Switchwire, but without a preliminary manual I'm sort of lost. No idea on how to use the parts and printable jigs...

**Comment by raymondh2** [comment]
There is an alpha version of the manual pinned in the Switchwire help channel on the Voron Discord.
