### ISSUE TITLE
Assembly manual does not show the SHCS bolt required for display assy

### ISSUE THREAD

**Issue by 3dRikal** [VoronDesign/Voron-Switchwire#50]
**OBSERVED**: On page 110 of the SW assembly manual, 2 SCHS bolts are required to set the display in place. 2 bolts are shown but no details are given

**EXPECTED**: Bolts should be labeled **M3x16 SHCS**

**Manual version reviewed:** 2021-11-26

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Switchwire/pull/59
