### ISSUE TITLE
Manual Page 70 - Mis-labeled M5 BHCS

### ISSUE THREAD

**Issue by sirjaymz** [VoronDesign/Voron-Switchwire#53]
![Mis-labeled BHSC pg 70](https://user-images.githubusercontent.com/7052158/226932289-0e6b0f5f-adfd-4fb9-8ff9-01730405adf9.jpg)

**Comment by asdasdwa-v02679** [comment]
Good catch, here is a updated version of the page plus a higher rez of just the edited assembly for the future convenience of the Manual team!
![sw page 70](https://github.com/VoronDesign/Voron-Switchwire/assets/133813592/5bdc7fd4-5581-42ce-b59a-bfcc51678510)
![sw page 70](https://github.com/VoronDesign/Voron-Switchwire/assets/133813592/4b2c6c87-5618-45df-b2f3-c7c50e85e6bf)

**Comment by nemgrea** [comment]
https://github.com/VoronDesign/Voron-Switchwire/pull/59
